[package]
name = "hanabi"
description = "Hanabi is a highly flexible and fast message broker and event streamer."
version = "0.1.0-alpha.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
publish.workspace = true

[dependencies]
hanabi-core = { workspace = true }

quinn = { workspace = true }

rustls = { workspace = true }