name: 'Release Workflow'
on:
  release:
    types:
      - published

jobs:
  publish:
    name: 'Publish'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
      - name: 'Install Rust'
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: 'Publish'
        run: cargo publish --workspace --all-features --locked --token ${{ secrets.CARGO_TOKEN }}